In [1]:
import numpy as np

# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

# <font color = red> ASSIGNMENT 1</font>
---

In [13]:
# using pythonic solutions
import numpy as np
A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

A1 = RowAdd(A,0,1,-2)
A2 = RowAdd(A1,0,2,-4)
A3 = RowAdd(A2,1,2,-2)
A4 = RowScale(A3,1,1.0/3)
A5 = RowScale(A4,2,1.0/-19.)
print(A5, '\n')


def back_sub(A):
    rows = A.shape[0]
    cols = A.shape[1]
    B = np.copy(A).astype('float64')
    for i in range(1, cols-1):
        row = cols - 1 - i
        for j in range(cols-i)
    return B
A6 = back_sub(A5)
print(A6)

[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]]
